version: '3.9'

services:
  api_app:
    build:
      context: ./api_app
    expose:
      - "8000"

  modsec_proxy:
    image: owasp/modsecurity-crs:nginx
    ports:
      - "8080:80"
    volumes:
      - ./modsecurity/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./modsecurity/modsecurity.conf:/etc/nginx/modsecurity.conf:ro
    depends_on:
      - api_app
